version: '3.0'

services:
  web:
   container_name: symfony_web
   build: ./Docker/Images/NGINX
   volumes:
          - ./app/:/var/www/app/
  #        - ./oauth2/server:/var/www/app/server/
  #        - ./site.conf:/etc/nginx/conf.d/site.conf
   links:
          - php
   ports:
          - "80:80"
   expose:
          - "80"
   environment:
          - "VIRTUAL_HOST=app.mmilko.git"
          - "VIRTUAL_PORT=8080"
   networks:
    net2:
      ipv4_address: 172.29.0.5
   extra_hosts:
          - "app.mmilko.git:172.29.0.5"
  php:
    container_name: symfony_php
    build: ./Docker/Images/PHP
    command: php-fpm
    volumes:
          - ./app/:/var/www/app/
    working_dir: /var/www/
    ports:
          - "9000:9000"
    links:
          - pgsql
          - elasticsearch
    networks:
     net2:
      ipv4_address: 172.29.0.6
    extra_hosts:
          - "app.mmilko.git:172.29.0.6"
  pgsql:
    container_name: symfony_pgsql
    build: ./Docker/Images/PgSql
    ports:
          - "5432:5432"
    environment:
      - DEBUG=false
      - DB_USER=
      - DB_PASS=
      - DB_NAME=
      - DB_TEMPLATE=
      - DB_EXTENSION=
      - REPLICATION_MODE=
      - REPLICATION_USER=
      - REPLICATION_PASS=
      - REPLICATION_SSLMODE=
    networks:
      net2:
       ipv4_address: 172.29.0.3
    restart: always
    expose:
      - "5432"
    volumes:
      - ./Docker/tmp/pgsql/data/db:/var/lib/postgresql
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.2
    container_name: symfony_elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./Docker/tmp/esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
     net2:
      ipv4_address: 172.29.0.2
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.2
    container_name: symfony_elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./Docker/tmp/esdata2:/usr/share/elasticsearch/data
    networks:
     net2:
      ipv4_address: 172.29.0.4
volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
networks:
  net2:
    driver: bridge
    ipam:
        driver: default
        config:
           - subnet: 172.29.0.0/16